name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Pack version"
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      attestations: write
    env:
      VERSION: ${{github.event.inputs.version}}
    steps:
      - name: checkout actions repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            META-INF
          path: "meta"
          ref: "1.7.0/main"

      - name: checkout resourcepack repository
        uses: actions/checkout@v6
        with:
          repository: "Complete-Cobblemon-Collection-Team/resourcepack"
          path: "resourcepack"
          ref: "1.7.0/dev"

      - name: checkout datapack repository
        uses: actions/checkout@v6
        with:
          repository: "Complete-Cobblemon-Collection-Team/datapack"
          path: "datapack"
          ref: "1.7.0/dev"

      - name: prepare 7-Zip
        uses: milliewalky/setup-7-zip@v2

      - name: prepare output
        run: |
          mkdir -p output/META-INF

      - name: render pack version to fabric.mod.json
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: 'meta/fabric.mod.json'
          output: 'output/fabric.mod.json'

      - name: render pack version to META-INF/neoforge.mods.toml
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: 'meta/META-INF/neoforge.mods.toml'
          output: 'output/META-INF/neoforge.mods.toml'

      - name: render pack version to pack.mcmeta
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: 'meta/pack.mcmeta'
          output: 'output/pack.mcmeta'

      - name: assemble artifacts
        run: |
          cp meta/Credits.txt output/
          cp meta/LICENSE output/
          cp meta/pack.png output/
          cp -r resourcepack/assets output/assets
          cp -r datapack/data output/data
          7z a -tzip CCC_$VERSION.jar -w output/. -xr!.git
          7z a -tzip CCC_$VERSION_datapack.zip -w output/. -xr!.git -xr!assets
          7z a -tzip CCC_$VERSION_resourcepack.zip -w output/. -xr!.git -xr!data

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Nightly"
          files: |
            output/CCC_$VERSION.jar
            output/CCC_$VERSION_datapack.zip
            output/CCC_$VERSION_resourcepack.zip